version: '3'

services:
  redis:
    image: redis

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=notSoSecure
      - POSTGRES_USER=defaultUser

  backend:
    image: backend
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=defaultUser
      - DB_PASSWORD=notSoSecure
      - DB_HOST=database
    restart: unless-stopped

  frontend:
    image: frontend

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
